application: climaticwebapp
version: live
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1

# Handlers define how to route requests to your application.
handlers:

# App Engine serves and caches static files contained in the listed directories
# (and subdirectories). Uncomment and set the directory as needed.
- url: /static
  static_dir: static

- url: /.*
  script: _go_app

