application: climaticwebapp 
version: 1
runtime: go
api_version: go1

# Handlers define how to route requests to your application.
handlers:

# App Engine serves and caches static files contained in the listed directories
# (and subdirectories). Uncomment and set the directory as needed.
- url: /static
  static_dir: static

- url: /.*
  script: _go_app

